### ISSUE TITLE
[Bug] `persist_docs` does not work for `materialized_view` materializations

### ISSUE THREAD

**Issue by morsapaes** [dbt-labs/dbt-postgres#120]
### Is this a new bug?

- [X] I believe this is a new bug
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

The macro that backs object-level `persist_docs` uses `{{ relation.type }}` to derive the object type in the `COMMENT ON` statement. This breaks for `materialized_view` materializations:

```bash
15:35:01  Database Error in model funds_movement (models/marts/funds_movement.sql)
15:35:01    Expected one of TABLE or VIEW or COLUMN or MATERIALIZED or SOURCE or SINK or INDEX or FUNCTION or CONNECTION or TYPE or SECRET or ROLE or DATABASE or SCHEMA or CLUSTER, found identifier "materialized_view"
15:35:01    LINE 5:   comment on materialized_view "marta"."public"."funds_moveme...
15:35:01                         ^
15:35:01    compiled Code at target/run/mz_get_started/models/marts/funds_movement.sql
15:35:01
15:35:01  Done. PASS=3 WARN=0 ERROR=2 SKIP=0 TOTAL=5
```

### Expected Behavior

The `persist_docs` config should work for `materialized_view` materializations.

### Steps To Reproduce

Attempt to use the `persist_docs` config with a materialized view model.

### Additional Context

We've fixed this a while back for `dbt-materialize` (which shims `dbt-postgres`) in [Materialize #21878](https://github.com/MaterializeInc/materialize/pull/21878), but it really should be fixed at the source! This issue was also reported by a user of the `dbt-risingwave` adapter ([`dbt-risingwave` #31](https://github.com/risingwavelabs/dbt-risingwave/issues/31)), which also shims `dbt-postgres`.

**Comment by jeremyyeo** [comment]
Previously reported https://github.com/dbt-labs/dbt-postgres/issues/11

**Comment by morsapaes** [comment]
Oh, sorry I missed that issue. Thank you, @jeremyyeo!
