### ISSUE TITLE
[CT-2860] [Feature] Add AWS IAM Authentication to dbt-postgres

### ISSUE THREAD

**Issue by christopherscholz** [dbt-labs/dbt-postgres#14]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

As with dbt-redshift, I would like to enable dbt-postgres to use AWS IAM Authentication. I use IAM Authentication for nearly everything and it just bugs me that it is available with dbt-redshift but not with dbt-postgres.

I envision the same setup as dbt-redshift. With a connection factory that returns a connection function.
This would easily allow other implementations as well.

The following profile configurations would change
- `password` becomes optional
- `method` is added: default `database`; options: `database`, `iam`
- `iam_profile` is added: default `None`, used to overwrite default AWS IAM profile
- `region` is added: default `None`, used to overwrite default AWS Region

If IAM is chosen as method, then before connecting to the PostgreSQL db using `psycopg2.connect`, it would
- open boto3 session
- create rds client
- get the auth token by calling generate_db_auth_token and pass it to kwargs as password

### Describe alternatives you've considered

Instead of implementing it in dbt, you could create a wrapper for dbt, which gets the token and passes it as a environment variable to dbt. Using env_var in the profile I could use this token as password.
But this token could only be used once. If during the run, the connection has to be reopened, this wouldn't work. Therefore I really don't like this this idea.

### Who will this benefit?

Everybody who is running dbt in AWS and is using IAM authentication for RDS PostgreSQL.

### Are you interested in contributing this feature?

Yes; Since this is my first contribution to dbt, please give me some guidance.

### Anything else?

There is a closed issue dbt-labs/dbt-core#3122, which was closed because it became stale. The author is asking for a implementation for IAM Authentication with Amazon Aurora PostgreSQL.
There is no difference in the IAM Authentication implementation for Amazon RDS Aurora PostgreSQL and Amazon RDS for PostgreSQL. Both work exactly the same.

**Comment by roitalpaz** [comment]
We would love to see this happen as well.
should we fork at our own organization? or would you prefer this to live at `dbt-labs`?

We can create a new fork which will be called `dbt-rds-postgres` with support of short lived aws IAM tokens.

**Comment by EitanKatsightfull** [comment]
@christopherscholz 
I have forked the repository and created this on our org
every session that is opened to the database has a fresh token
https://github.com/sightfullco/dbt-postgres-rds/tree/feature/postgresrds-adapter

**Comment by colin-rogers-dbt** [comment]
Closing this out as we view this as outside the scope of dbt-postgres as an adapter.

**Comment by dmunch** [comment]
At least you'll make our lives not too hard in maintaining forks by not moving repositories too often - I've just learned that https://github.com/dbt-labs/dbt-postgres is already deprecated in favour of https://github.com/dbt-labs/dbt-adapters/tree/main/dbt-postgres

https://github.com/dbt-labs/dbt-postgres/pull/192/
