### ISSUE TITLE
[Bug] Pull requests depending on branch in dbt-adapters are not fully working

### ISSUE THREAD

**Issue by dbeatty10** [dbt-labs/dbt-postgres#43]
### Is this a new bug?

- [X] I believe this is a new bug
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

It's tricky to have a PR in dbt-postgres that depends on a branch in dbt-adapters and allows all CI checks to execute.

See internal slack for initial context: https://dbt-labs.slack.com/archives/C034EV1RH4Z/p1712161174778999?thread_ts=1711994615.204219&cid=C034EV1RH4Z

### Expected Behavior

There should be a mechanism with a similar effect as https://github.com/dbt-labs/dbt-postgres/commit/bc0b1797d868fa674e67069c59e4dc5d929e23ed that allows for (temporarily) using a dev branch in dbt-adapters for testing purposes.

### Environment

```markdown
- OS:
- Python:
- dbt-postgres:
```

### Additional Context

Here's an example:

https://github.com/dbt-labs/dbt-postgres/pull/39 needs the branch from https://github.com/dbt-labs/dbt-adapters/pull/135 in order to do its testing.

**Comment by colin-rogers-dbt** [comment]
Work needed: Update pyproject.toml and hatch to load from a set of customizable dev requirement

**Comment by dbeatty10** [comment]
Here's the exact changes I needed to make: https://github.com/dbt-labs/dbt-postgres/commit/bc0b1797d868fa674e67069c59e4dc5d929e23ed
