### ISSUE TITLE
[Bug] unordered set causing statements to be executed in incorrect order

### ISSUE THREAD

**Issue by colin-rogers-dbt** [dbt-labs/dbt-postgres#72]
### Is this a new bug?

- [X] I believe this is a new bug
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

We use a `set` object to store SQL statements to be executed as part of an index operation. Because this is unordered this will occassionally cause us to execute statements in the wrong order.
See: https://github.com/dbt-labs/dbt-postgres/blob/6a1897e6b00a60ae8c9ad762453b3a31ff244d2d/dbt/adapters/postgres/relation.py#L78

### Expected Behavior

Statements are ordered correctly

### Steps To Reproduce

Run this a couple of times:
```
 hatch run integration-tests:all tests/functional/materializations/materialized_view_tests/test_materialized_view.py::TestPostgresMaterializedViewChangesApply
```

### Environment

```markdown
- OS:
- Python:
- dbt-postgres:
```

**Comment by mikealfare** [comment]
Re-opening for the backport.
