### ISSUE TITLE
[Bug] `latest` and `1.x.latest` tags for ghcr Docker releases are stale

### ISSUE THREAD

**Issue by dbeatty10** [dbt-labs/dbt-postgres#9]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Look at https://github.com/dbt-labs/dbt-postgres/pkgs/container/dbt-postgres/versions?filters%5Bversion_type%5D=tagged

1.2.3 is tagged as latest:

<img width="283" alt="image" src="https://github.com/dbt-labs/dbt-core/assets/44704949/2d468880-5d2d-4ac3-bf42-810439c73d0d">

### Expected Behavior

1.7.6 is tagged as `latest` and `1.7.latest`:

<img width="243" alt="image" src="https://github.com/dbt-labs/dbt-core/assets/44704949/2eeedfc8-0e3e-4dad-8c91-88a0297e5f30">

And the rest of the 1.x minor versions have `1.x.latest` tags as well.

### Steps To Reproduce

See current behavior above.

### Environment

```markdown
- OS:
- Python:
- dbt:
```

### Which database adapter are you using with dbt?

postgres

**Comment by mikealfare** [comment]
I'm throwing this in this sprint since I'm going on support. I'll verify that the labels appear correctly.

**Comment by mikealfare** [comment]
These tags have been updated due to releasing `dbt-postgres`.
