### ISSUE TITLE
[Regression] Forced psycopg2 dependency on Linux causes sudden build failures

### ISSUE THREAD

**Issue by mateusz** [dbt-labs/dbt-postgres#96]
### Is this a regression?

- [X] I believe this is a regression in functionality
- [X] I have searched the existing issues, and I could not find an existing issue for this regression

### Current Behavior

My existing build system now breaks due to introduction of hard `psycopg2` dependency into pyproject.toml in 1.8.0 in #60 , which forces `psycopg2` compilation from source on Linux, which hasn't got the dependencies installed in my docker image, which breaks the build. My desired production setup is psycopg2-binary (for consistency), and I do not wish to build psycopg2 from source (because I don't want the dev dependencies).

### Expected/Previous Behavior

I expect a minor release to not break an existing build system, and I expect the same psycopg2 variant to be used across dev and prod for quality reasons (replicable build).

### Steps To Reproduce

1. On an existing psycopg2-binary setup, update dbt-postgres to 1.8.0.

### Relevant log output

```shell
#0 21.05   ChefBuildError
#0 21.05 
#0 21.05   Backend subprocess exited when trying to invoke get_requires_for_build_wheel
#0 21.05   
#0 21.05   running egg_info
#0 21.05   writing psycopg2.egg-info/PKG-INFO
#0 21.05   writing dependency_links to psycopg2.egg-info/dependency_links.txt
#0 21.05   writing top-level names to psycopg2.egg-info/top_level.txt
#0 21.05   
#0 21.05   Error: pg_config executable not found.
#0 21.05   
#0 21.05   pg_config is required to build psycopg2 from source.  Please add the directory
#0 21.05   containing pg_config to the $PATH or specify the full executable path with the
#0 21.05   option:
#0 21.05   
#0 21.05       python setup.py build_ext --pg-config /path/to/pg_config build ...
#0 21.05   
#0 21.05   or with the pg_config option in 'setup.cfg'.
#0 21.05   
#0 21.05   If you prefer to avoid building psycopg2 from source, please install the PyPI
#0 21.05   'psycopg2-binary' package instead.
#0 21.05   
#0 21.05   For further information please check the 'doc/src/install.rst' file (also at
#0 21.05   <https://www.psycopg.org/docs/install.html>).
```

### Environment

```markdown
- OS: Mac
- Python: 3.9
- dbt-postgres (working version): 1.7.14
- dbt-postgres (regression version): 1.8.0
```

### Additional Context

There is also a [comment here](https://github.com/dbt-labs/dbt-postgres/commit/32c8547ae42169f8147c5fbec2712c22b7f9db33#r142012438) from @andy-clapson challenging Linux=prod assumption.

**Comment by mateusz** [comment]
Is there a workaround that would let me force `psycopg2-binary`? I have to currently resort to editing my `poetry.lock` which isn't too nice 😁

**Comment by andy-clapson** [comment]
second this regression - this fix should be reverted and the use case handled differently.

**Comment by mateusz** [comment]
Thank you for your in-depth answer and understanding. I had a quick look at providing optional deps via `extras`, but didn't find anything over what you already provided. 

Philosophically speaking, 1.8.0 is already backwards-incompatible and so perhaps there is a case here to embrace this, explain to the community, and switch to the most pythonic approach that's best for the long run?

**Comment by farovictor** [comment]
To anyone that needs a working solution and doesn't care about using a bin version of Postgres connector. I have forked this repo and updated the readme with instructions so you can build your package. Here is the link: https://github.com/farovictor/dbt-postgres

If you do not want to pull the fork you still can do it by yourself, pull official repo and do this:

1. Change the dependency definition for psycopg2 in pyproject.toml, to look like this:
```toml
dependencies = [
    "psycopg2-binary>=2.9,<3.0",
    ...
```
Change yourself or just clone the repo I provided above.

2. Install hatch on your system or environment:
```bash
pip install hatch
```

3. Build the package
```bash
hatch build
```

4. Install dot-postgres from your wheel file located in the dist folder, created during the build process.

Be happy.

**Comment by jtcohen6** [comment]
To follow up here, after some more investigation and discussion, this is the approach we've landed on:
> we should make `psycopg2-binary` the default across the board, even for Linux. For production pipelines, we would then recommend that users add `pip uninstall psycopg2-binary && pip install psycopg2` (and hope all transitive dependencies work). This is ugly, but it replicates the previous "opt-in" behavior, via two additional pip commands instead of setting `DBT_PSYCOPG2_NAME=psycopg2`.

**Comment by georgek** [comment]
I think that's a reasonable compromise. Just out of interest, would use of `psycopg` (v3) make things easier at all?
