### ISSUE TITLE
[Tech debt] Add Postgres container for development so that integration tests can be run via Docker

### ISSUE THREAD

**Issue by mikealfare** [dbt-labs/dbt-postgres#99]
### Is this your first time submitting a feature request?

- [X] I have read the expectations for open source contributors
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-postgres functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Running integration tests against Postgres requires a manual setup of Postgres locally. It would be nice if this were automated, especially for community contributors that may not have Postgres always running locally. Additionally, this would support developing in a Docker container via `docker/dev.Dockerfile` since the connection credentials and parameters would all be deterministic.

### Describe alternatives you've considered

We could do nothing. This would leave in the current state:
- developers must manually setup Postgres for integration tests
- development via the provided Docker container would not be able to run integration tests

### Who will this benefit?

Any contributors to `dbt-postgres`, including maintainers.

**Comment by jtcohen6** [comment]
@mikealfare Do you see this as being the same or different from what we have in `dbt-core` today?
- https://github.com/dbt-labs/dbt-core/blob/main/docker-compose.yml
- https://github.com/dbt-labs/dbt-core/blob/341803d78454f26932267b4c5da361c83556e96a/Makefile#L101-L105

**Comment by mikealfare** [comment]
> @mikealfare Do you see this as being the same or different from what we have in `dbt-core` today?
> 
>     * https://github.com/dbt-labs/dbt-core/blob/main/docker-compose.yml
> 
>     * https://github.com/dbt-labs/dbt-core/blob/341803d78454f26932267b4c5da361c83556e96a/Makefile#L101-L105

Ah, I didn't realize we already had that. Yes, it would probably be very similar. I would just set that up in the `dbt-postgres` repo and then make sure we could use it with the local virtual environment as well as a dev Docker environment.
